plugins {
    id 'java'
    id 'war'
}

group = 'com.naloga'
version = '1'

compileJava.options.encoding = 'UTF-8'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}
dependencies {
    compileOnly (
            'javax:javaee-web-api:7.0',
    )
    implementation (
            'org.springframework:spring-webmvc:5.3.14',
            'org.thymeleaf:thymeleaf:3.0.14.RELEASE',
            'org.thymeleaf:thymeleaf-spring5:3.0.14.RELEASE',
    )
}

tasks.named('test') {
    useJUnitPlatform()
}
